### ISSUE TITLE
Getting 404 page not found of root of website(https://nuxt.sushilgc.com.np)

### ISSUE THREAD

**Issue by sushiljic** [RightBrainTechBD/nuxt-template-for-shared-hosting#1]
I have tried the same .httacess but getting 
404 when hitting url(https://nuxt.sushilgc.com.np), while i found everything else is working.
My .htaccess is 
RewriteEngine on

# Forcing all incoming requests to HTTPS. 
# HTTPS is required for PWA. If you don't want PWA feature you can deisable next 2 lines
 
RewriteCond %{HTTPS} !on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

DirectoryIndex index.html

RewriteRule ^$ http://127.0.0.1:3000/ [P,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ http://127.0.0.1:3000/$1 [P,L]

You can also test the site
https://nuxt.sushilgc.com.np

**Comment by who-jonson** [comment]
Sorry for late reply. But when checking your given url, this is looking right. Is there still any problem ?
